@echo off
REM ****************************************************************************
REM Vivado (TM) v2020.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Mon Jun 17 16:04:53 +0800 2024
REM SW Build 3064766 on Wed Nov 18 09:12:45 MST 2020
REM
REM Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim tb_icmp_behav -key {Behavioral:sim_1:Functional:tb_icmp} -tclbatch tb_icmp.tcl -view E:/Master/FPGA/1_Prj/PL_ethernet_video_transmission_system_based_on_ov5640/3_eth_icmp_test/prj/tb_icmp_behav.wcfg -log simulate.log"
call xsim  tb_icmp_behav -key {Behavioral:sim_1:Functional:tb_icmp} -tclbatch tb_icmp.tcl -view E:/Master/FPGA/1_Prj/PL_ethernet_video_transmission_system_based_on_ov5640/3_eth_icmp_test/prj/tb_icmp_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
