######################################################################
#
# File name : tb_mdio_rw_test_simulate.do
# Created on: Sun Jun 25 15:34:19 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -lib xil_defaultlib xil_defaultlib.tb_mdio_rw_test xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {tb_mdio_rw_test_wave.do}

view wave
view structure
view signals

do {tb_mdio_rw_test.udo}

run 1000ns
