######################################################################
#
# File name : tb_mdio_rw_test_wave.do
# Created on: Sun Jun 25 15:34:19 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
