# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/FPGA/ov5640_udp_pc/ov5640_udp_pc.srcs/sources_1/ip/async_fifo_2048x8b/async_fifo_2048x8b.xci
# IP: The module: 'async_fifo_2048x8b' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/FPGA/ov5640_udp_pc/ov5640_udp_pc.srcs/sources_1/ip/async_fifo_2048x8b/async_fifo_2048x8b.xdc
# XDC: The top module name and the constraint reference have the same name: 'async_fifo_2048x8b'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/FPGA/ov5640_udp_pc/ov5640_udp_pc.srcs/sources_1/ip/async_fifo_2048x8b/async_fifo_2048x8b_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'async_fifo_2048x8b'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/FPGA/ov5640_udp_pc/ov5640_udp_pc.srcs/sources_1/ip/async_fifo_2048x8b/async_fifo_2048x8b_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'async_fifo_2048x8b'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/FPGA/ov5640_udp_pc/ov5640_udp_pc.srcs/sources_1/ip/async_fifo_2048x8b/async_fifo_2048x8b.xci
# IP: The module: 'async_fifo_2048x8b' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/FPGA/ov5640_udp_pc/ov5640_udp_pc.srcs/sources_1/ip/async_fifo_2048x8b/async_fifo_2048x8b.xdc
# XDC: The top module name and the constraint reference have the same name: 'async_fifo_2048x8b'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/FPGA/ov5640_udp_pc/ov5640_udp_pc.srcs/sources_1/ip/async_fifo_2048x8b/async_fifo_2048x8b_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'async_fifo_2048x8b'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/FPGA/ov5640_udp_pc/ov5640_udp_pc.srcs/sources_1/ip/async_fifo_2048x8b/async_fifo_2048x8b_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'async_fifo_2048x8b'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
