# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/eth_icmp_test.xdc

# IP: ip/sync_fifo_2048x8b/sync_fifo_2048x8b.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sync_fifo_2048x8b || ORIG_REF_NAME==sync_fifo_2048x8b} -quiet] -quiet
