######################################################################
#
# File name : eth_arp_test_wave.do
# Created on: Wed May 31 13:11:38 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
