######################################################################
#
# File name : eth_arp_test_compile.do
# Created on: Wed May 31 13:11:35 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/xpm
vlib modelsim_lib/msim/xil_defaultlib

vmap xpm modelsim_lib/msim/xpm
vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

vlog  -incr -sv -work xpm  "+incdir+../../../../eth_arp_test.gen/sources_1/ip/clk_wiz_0" \
"D:/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
"D:/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \

vcom  -93 -work xpm  \
"D:/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_VCOMP.vhd" \

vlog  -incr -work xil_defaultlib  "+incdir+../../../../eth_arp_test.gen/sources_1/ip/clk_wiz_0" \
"../../../../eth_arp_test.gen/sources_1/ip/ila_arp_rx/sim/ila_arp_rx.v" \
"../../../../eth_arp_test.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_clk_wiz.v" \
"../../../../eth_arp_test.gen/sources_1/ip/clk_wiz_0/clk_wiz_0.v" \
"../../../../../rtl/arp/arp.v" \
"../../../../../rtl/arp_ctrl.v" \
"../../../../../rtl/arp/arp_rx.v" \
"../../../../../rtl/arp/arp_tx.v" \
"../../../../../rtl/arp/crc32_d8.v" \
"../../../../../rtl/gmii_to_rgmii/gmii_to_rgmii.v" \
"../../../../../rtl/gmii_to_rgmii/rgmii_rx.v" \
"../../../../../rtl/gmii_to_rgmii/rgmii_tx.v" \
"../../../../../rtl/eth_arp_test.v" \

# compile glbl module
vlog -work xil_defaultlib "glbl.v"

quit -force

