######################################################################
#
# File name : eth_arp_test_simulate.do
# Created on: Wed May 31 13:11:38 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L xpm -L unisims_ver -L unimacro_ver -L secureip -lib xil_defaultlib xil_defaultlib.eth_arp_test xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {eth_arp_test_wave.do}

view wave
view structure
view signals

do {eth_arp_test.udo}

run 1000ns
