######################################################################
#
# File name : tb_arp_wave.do
# Created on: Wed May 31 13:12:05 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
