######################################################################
#
# File name : tb_arp_compile.do
# Created on: Sun Jun 25 16:10:42 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
C:\\modeltech64_10.5\\win64\\vlib modelsim_lib/work
C:\\modeltech64_10.5\\win64\\vlib modelsim_lib/msim

C:\\modeltech64_10.5\\win64\\vlib modelsim_lib/msim/xil_defaultlib

C:\\modeltech64_10.5\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

C:\\modeltech64_10.5\\win64\\vlog  -incr -work xil_defaultlib  \
"../../../../../rtl/arp/arp.v" \
"../../../../../rtl/arp/arp_rx.v" \
"../../../../../rtl/arp/arp_tx.v" \
"../../../../../rtl/arp/crc32_d8.v" \
"../../../../../sim/tb/tb_arp.v" \


# compile glbl module
C:\\modeltech64_10.5\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

