######################################################################
#
# File name : tb_icmp_wave.do
# Created on: Sun Jun 25 16:39:22 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
