######################################################################
#
# File name : tb_icmp_compile.do
# Created on: Thu Jun 29 09:10:13 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
C:\\modeltech64_10.5\\win64\\vlib modelsim_lib/work
C:\\modeltech64_10.5\\win64\\vlib modelsim_lib/msim

C:\\modeltech64_10.5\\win64\\vlib modelsim_lib/msim/xil_defaultlib

C:\\modeltech64_10.5\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

C:\\modeltech64_10.5\\win64\\vlog  -incr -work xil_defaultlib  "+incdir+../../../../eth_icmp_test.gen/sources_1/ip/clk_wiz_0" \
"../../../../../rtl/arp/crc32_d8.v" \
"../../../../../rtl/icmp/icmp.v" \
"../../../../../rtl/icmp/icmp_rx.v" \
"../../../../../rtl/icmp/icmp_tx.v" \
"../../../../../sim/tb_icmp.v" \


# compile glbl module
C:\\modeltech64_10.5\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

