######################################################################
#
# File name : tb_icmp_simulate.do
# Created on: Thu Jun 29 09:10:15 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -L xpm -lib xil_defaultlib xil_defaultlib.tb_icmp xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {tb_icmp_wave.do}

view wave
view structure
view signals

do {tb_icmp.udo}

run 1000ns
