######################################################################
#
# File name : tb_mdio_rw_test_compile.do
# Created on: Sun Jun 25 15:34:17 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
C:\\modeltech64_10.5\\win64\\vlib modelsim_lib/work
C:\\modeltech64_10.5\\win64\\vlib modelsim_lib/msim

C:\\modeltech64_10.5\\win64\\vlib modelsim_lib/msim/xil_defaultlib

C:\\modeltech64_10.5\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

C:\\modeltech64_10.5\\win64\\vlog  -incr -work xil_defaultlib  \
"../../../../../rtl/mdio_ctrl.v" \
"../../../../../rtl/mdio_dri.v" \
"../../../../../rtl/mdio_rw_test.v" \
"../../../../../sim/mdio_slave_interface.v" \
"../../../../../sim/tb_mdio_rw_test.v" \


# compile glbl module
C:\\modeltech64_10.5\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

